[package]
authors = ["Zack Owens <zowens2009@gmail.com>"]
name = "paxos"
version = "0.1.0"

[dependencies]
log = "0.4"
rand = { version = "0.7", features = ["small_rng"] }
tokio = { version = "0.2", features = ["full"] }
futures = "0.3"
env_logger = "0.7"
clap = "2.33.0"
either = "1.5.3"
serde_derive = "1.0.103"
serde_cbor = "0.10"
serde = "1.0.103"
bytes = "0.5"

[dev-dependencies]
assert_matches = "1.1.0"
